name: i-do

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: shimmerjs
          password: ${{ secrets.CONTAINER_STUFF_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shimmerjs/fralex.life:bigday-${{ github.sha }}
      - name: glotify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: |
            ${{ github.actor }} pushed ${{ github.sha },
            which published 
            shimmerjs/fralex.life@${{ steps.docker_build.outputs.digest }}

            thank you for doing your part, 10 fralexcoins have been credited to your wallet